// Original by CantBeFaraz
// https://twitter.com/CantBeFaraz/status/1678007542817882112

import { useEffect } from 'react'
import { Canvas } from '@react-three/fiber'
import { useGLTF, useAnimations, ContactShadows, Environment, PerspectiveCamera } from '@react-three/drei'
import { EffectComposer, Bloom } from '@react-three/postprocessing'
import { DissolveMaterial } from './DissolveMaterial'

export default function App() {
  return (
    <Canvas>
      <PerspectiveCamera makeDefault position={[0, 2, 8]} fov={40} />
      <Model />
      <Environment background preset="city" blur={0.8} />
      <EffectComposer disableNormalPass>
        <Bloom luminanceThreshold={1} intensity={1.25} mipmapBlur />
      </EffectComposer>
    </Canvas>
  )
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: StrykerDoesAnimation (https://sketchfab.com/strykerdoesgames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dancing-stormtrooper-12bd08d66fe04a84be446e583d6663ac
Title: DANCING STORMTROOPER
*/
function Model(props) {
  const { nodes, materials, animations } = useGLTF('/dancing_stormtrooper.glb')
  const { ref, actions } = useAnimations(animations)
  useEffect(() => void actions['mixamo.com'].play(), [actions])
  return (
    <group name="Sketchfab_Scene" ref={ref} dispose={null} {...props}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <group name="f8ce42897676455090b6ff376356f84cfbx" rotation={[Math.PI / 2, 0, 0]}>
          <group name="Object_2">
            <group name="RootNode">
              <group name="Object_4">
                <primitive object={nodes._rootJoint} />
                <skinnedMesh castShadow name="Object_7" geometry={nodes.Object_7.geometry} skeleton={nodes.Object_7.skeleton}>
                  <DissolveMaterial baseMaterial={materials.Stormtroopermat} />
                </skinnedMesh>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dancing_stormtrooper.glb')
